### ISSUE TITLE
grpcurl - throws error

### ISSUE THREAD

**Issue by killabit** [Leask/Starlink-Signal-Status#2]
I can't find much in helping resolve this error but I am getting the following on startup..

{"time":"2023-04-03T07:21:33.078Z","message":"Failed to dial target host \"192.168.100.1:9200\": context deadline exceeded\n"}                                                                                                                                                x
x{"time":"2023-04-03T07:21:34.077Z","message":"Failed to dial target host \"192.168.100.1:9200\": context deadline exceeded\n"}                                                                                                                                                x
x{"time":"2023-04-03T07:21:35.083Z","message":"Failed to dial target host \"192.168.100.1:9200\": context deadline exceeded\n"}      

Any idea? Anytime I try to talk to the dish I get this.. Stats work using some scripts and grafana so I am sure it isnt my dish or config..                     

![image](https://user-images.githubusercontent.com/51775887/229439106-f53cae5e-fa16-49d4-904f-7089ab8b5401.png)

**Comment by killabit** [comment]
Fixed this error, local routing table was allowing icmp but no tcp...

**Comment by Leask** [comment]
👍
