### ISSUE TITLE
npm deprecated warnings

### ISSUE THREAD

**Issue by Mudary** [Leask/Starlink-Signal-Status#3]
Doesn't install unless you use sudo or sudo su. Thanks

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by Leask** [comment]
Using sudo is unnecessary unless the permissions for the npm folder are incorrectly set.

Additionally, while many packages have indeed been deprecated, this is not a major issue. We do not plan to address it at this time but will monitor the project's progress.

Thank you!
